#!/usr/bin/env python3
"""Open sync PRs against all 8 downstream repos.

Environment variables required:
  GH_TOKEN       Fine-grained PAT with contents:write and pull_requests:write
  CANONICAL_SHA  Full SHA of the canonical commit
  SHORT_SHA      Short SHA for branch names
  DRY_RUN        'true' to skip push and PR creation
"""
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BUILD_DIR = REPO_ROOT / "build"

DOWNSTREAM_REPOS = [
    {
        "repo": "Open-Paws/eslint-plugin-no-animal-violence",
        "branch": "main",
        "files": {
            "lib/rules/no-violent-language.js": "eslint-plugin-no-animal-violence/lib/rules/no-violent-language.js",
        },
    },
    {
        "repo": "Open-Paws/semgrep-rules-no-animal-violence",
        "branch": "master",
        "files": {
            "rules/animal-violence-generic.yaml": "semgrep-rules-no-animal-violence/rules/animal-violence-generic.yaml",
            "rules/animal-violence-python.yaml": "semgrep-rules-no-animal-violence/rules/animal-violence-python.yaml",
            "rules/animal-violence-javascript.yaml": "semgrep-rules-no-animal-violence/rules/animal-violence-javascript.yaml",
            "rules/animal-violence-go.yaml": "semgrep-rules-no-animal-violence/rules/animal-violence-go.yaml",
        },
    },
    {
        "repo": "Open-Paws/vale-no-animal-violence",
        "branch": "main",
        "files": {
            "NoAnimalViolence/AnimalIdioms.yml": "vale-no-animal-violence/NoAnimalViolence/AnimalIdioms.yml",
            "NoAnimalViolence/meta.json": "vale-no-animal-violence/NoAnimalViolence/meta.json",
        },
    },
    {
        "repo": "Open-Paws/no-animal-violence-pre-commit",
        "branch": "main",
        "files": {
            "no_animal_violence_check.py": "no-animal-violence-pre-commit/no_animal_violence_check.py",
        },
    },
    {
        "repo": "Open-Paws/no-animal-violence-action",
        "branch": "main",
        "files": {
            "action.yml": "no-animal-violence-action/action.yml",
        },
    },
    {
        "repo": "Open-Paws/reviewdog-no-animal-violence",
        "branch": "main",
        "files": {
            "action.yml": "reviewdog-no-animal-violence/action.yml",
        },
    },
    {
        "repo": "Open-Paws/danger-plugin-no-animal-violence",
        "branch": "main",
        "files": {
            "src/index.ts": "danger-plugin-no-animal-violence/src/index.ts",
        },
    },
    {
        "repo": "Open-Paws/vscode-no-animal-violence",
        "branch": "main",
        "files": {
            "extension.js": "vscode-no-animal-violence/extension.js",
        },
    },
]


def run(cmd, **kwargs):
    return subprocess.run(cmd, check=True, capture_output=True, text=True, **kwargs)


def propagate_repo(config: dict, sync_branch: str, canonical_sha: str, dry_run: bool) -> dict:
    repo = config["repo"]
    base_branch = config["branch"]
    result = {"repo": repo, "status": "unknown", "pr_url": None, "error": None}

    with tempfile.TemporaryDirectory() as tmpdir:
        try:
            token = os.environ["GH_TOKEN"]
            clone_url = f"https://x-access-token:{token}@github.com/{repo}.git"
            run(["git", "clone", "--depth=1", "-b", base_branch, clone_url, tmpdir])

            changed = False
            for dest_path, build_rel in config["files"].items():
                src = BUILD_DIR / build_rel
                dst = Path(tmpdir) / dest_path
                if not src.exists():
                    result["status"] = "build_missing"
                    result["error"] = f"Build output missing: {src}"
                    return result
                dst.parent.mkdir(parents=True, exist_ok=True)
                new_content = src.read_text()
                if dst.exists() and dst.read_text() == new_content:
                    continue
                dst.write_text(new_content)
                changed = True

            if not changed:
                result["status"] = "no_changes"
                return result

            if dry_run:
                result["status"] = "dry_run"
                return result

            run(["git", "checkout", "-b", sync_branch], cwd=tmpdir)
            run(["git", "config", "user.email", "sync-bot@openpaws.ai"], cwd=tmpdir)
            run(["git", "config", "user.name", "Open Paws Sync Bot"], cwd=tmpdir)
            run(["git", "add", "-A"], cwd=tmpdir)
            run(
                ["git", "commit", "-m",
                 f"sync: regenerate from canonical {canonical_sha[:12]}\n\nGenerated by propagate.yml in Open-Paws/no-animal-violence@{canonical_sha}"],
                cwd=tmpdir,
            )
            run(["git", "push", "origin", sync_branch], cwd=tmpdir)

            pr_result = run(
                ["gh", "pr", "create",
                 "--repo", repo,
                 "--base", base_branch,
                 "--head", sync_branch,
                 "--title", f"sync: update rules from canonical {canonical_sha[:12]}",
                 "--body", f"Automated sync from Open-Paws/no-animal-violence@{canonical_sha}.\n\nThis PR was opened by the `propagate.yml` workflow. Rule definitions live in the canonical repo — edit there, not here.\n\nSee [AUTOSYNC.md](.github/AUTOSYNC.md) for details.",
                 "--label", "automated-sync"],
                cwd=tmpdir,
                env={**os.environ, "GH_TOKEN": token},
            )
            result["pr_url"] = pr_result.stdout.strip()
            result["status"] = "pr_opened"

        except subprocess.CalledProcessError as exc:
            result["status"] = "error"
            result["error"] = exc.stderr[:500]

    return result


def main() -> int:
    canonical_sha = os.environ.get("CANONICAL_SHA", "unknown")
    short_sha = os.environ.get("SHORT_SHA", "unknown")
    dry_run = os.environ.get("DRY_RUN", "false").lower() == "true"
    sync_branch = f"sync/canonical-{short_sha}"

    results = []
    for config in DOWNSTREAM_REPOS:
        print(f"Processing {config['repo']}...", flush=True)
        r = propagate_repo(config, sync_branch, canonical_sha, dry_run)
        results.append(r)
        print(f"  -> {r['status']}" + (f": {r['pr_url']}" if r.get("pr_url") else ""))

    print("\n=== Propagation Summary ===")
    succeeded = [r for r in results if r["status"] in ("pr_opened", "no_changes", "dry_run")]
    failed = [r for r in results if r not in succeeded]

    for r in results:
        icon = "OK" if r["status"] in ("pr_opened", "no_changes") else "FAIL"
        print(f"  [{icon}] {r['repo']}: {r['status']}")
        if r.get("pr_url"):
            print(f"      PR: {r['pr_url']}")
        if r.get("error"):
            print(f"      Error: {r['error']}")

    if failed:
        print(f"\n{len(failed)} repo(s) failed.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
